### ISSUE TITLE
Tutorial notebook not working

### ISSUE THREAD

**Issue by mstaczek** [rachtibat/zennit-crp#1]
Hi, I am trying to run code from tutorial notebooks. I got stuck in notebook [attributions.ipynb](https://github.com/rachtibat/zennit-crp/blob/master/tutorials/attributions.ipynb) at line:
>  `attr = attribution(sample, conditions, composite, mask_map=cc.mask)` 

with an error saying :
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> t:\studies\py_projects\milab-internship\clean-zennit-crp\tutorials\attributions.ipynb Cell 20 in <cell line: 8>()
>       6 # zennit requires gradients
>       7 sample.requires_grad = True
> ----> 8 attr = attribution(sample, conditions, composite, mask_map=cc.mask)
>      10 # or use a dictionary for mask_map
>      11 layer_names = get_layer_names(model, [torch.nn.Conv2d, torch.nn.Linear])
> 
> File t:\win_programs\python_venvs\ml_39_torch_171\lib\site-packages\crp\attribution.py:154, in CondAttribution.__call__(self, data, conditions, composite, record_layer, mask_map, start_layer, init_rel, on_device)
>     152 else:
>     153     pred = modified(data)
> --> 154     self.backward_initialization(pred, y_targets, init_rel, self.MODEL_OUTPUT_NAME)
>     156 attribution = self.attribution_modifier(data)
>     157 activations, relevances = {}, {}
> 
> File t:\win_programs\python_venvs\ml_39_torch_171\lib\site-packages\crp\attribution.py:64, in CondAttribution.backward_initialization(self, prediction, target_list, init_rel, layer_name, retain_graph)
>      61         mask[i, targets] = output_selection[i, targets]
>      62     output_selection = mask
> ---> 64 torch.autograd.backward((prediction,), (output_selection.to(prediction),),
>      65                         retain_graph=retain_graph)
> ...
> [too long to paste here]
> ...
>      40         New Tensor copied from `input` with values shifted by epsilon.
>      41     '''
> ---> 42     return input + ((input == 0.).to(input) + input.sign()) * epsilon
> 
> TypeError: only integer tensors of a single element can be converted to an index

System details:

Platform: 	Windows 11
Python:		Python 3.9.13
Pytorch: 	torch==1.7.1+cu110

Also tried with:
	- Python 3.10 with torch 1.12.0 and CUDA 11.6 (on Windows),
	- Python 3.8 with torch 1.7 and CUDA 10.2 (on Ubuntu)
with same results.

**Comment by rachtibat** [comment]
Hi,

Thank you for your interest in our library!

I think the problem is caused by an incompatibility with the new zennit release. 
Unfortunately, I have not been able to look at the cause yet, but another colleague of mine was able to solve the problem by downgrading to an older release.

Try out zennit release [0.4.6](https://github.com/chr5tphr/zennit/releases/tag/0.4.6) or an older one.

Please let me know if it worked!

Best greetings,
Reduan

**Comment by mstaczek** [comment]
Hi, it solved my issue, thanks!
