### ISSUE TITLE
Relevance of weight values

### ISSUE THREAD

**Issue by shivmgg** [rachtibat/zennit-crp#12]
Hi, 

Thanks for the awesome work! Is there any way to extend relevance scores for activations in each layer to their corresponding weight values?

**Comment by rachtibat** [comment]
Hi,

Thanks for your interesting request! Unfortunately, zennit at its current status does not support relevance assignments for weights. However, you could change its source code to support this type of assignments. In addition, you can ask the maintainer of the zennit project if he could guide you to the right direction.

zennit-crp builds upon zennit and hence the same limitations apply to zennit-crp.

Hope you find an easy way,
Reduan

**Comment by shivmgg** [comment]
Thanks Reduan for your suggestions! I will take a look at the original repo and see if I can extend the project.
