### ISSUE TITLE
`layer_map` variable in Code Example

### ISSUE THREAD

**Issue by Paula-Kli** [rachtibat/zennit-crp#26]
Hey!
is it possible that in your Readme in the Feature Visualization Part the line `layer_map = {(name, cc) for name in layer_names}` should actually be `layer_map = {name: cc for name in layer_names}`?

In `crp/visualization.py` in line 103 the code wants to iterate over `self.layer_map.items()` which is not available if this is used as a set. If you change the code as depicted above it becomes a dictionary and on dictionaries `.items()`is available.

Did I see that correctly or did I miss something?

Thanks!

**Comment by rachtibat** [comment]
Hey, 

thanks! This is correct. You can create a pull request if you like!
