### ISSUE TITLE
Target list needs to be a numpy array for multi-target datasets

### ISSUE THREAD

**Issue by maxdreyer** [rachtibat/zennit-crp#5]
Hi all,

for a multi-target dataset, I get the following error:

```
File ".../crp/visualization.py", line 180, in analyze_activation
    targets = targets[unique_indices]
TypeError: only integer scalar arrays can be converted to a scalar index
```

This is resulting as the list targets need to be a numpy array. This is the case for single-target datasets, where the conversion from List to numpy array is taking place in line 118 of ".../crp/visualization.py":
```
targets_samples = np.array(targets_samples)  # numpy operation needed
```
Therefore, we also have to add a statement such as 
```
targets = np.array(targets)
```
after line 133 of ".../crp/visualization.py".

**Comment by rachtibat** [comment]
Hi Max,

thanks, you're right. If you want, you can create a pull request and add your code at line 134.
Otherwise, I can do that.

Best
