### ISSUE TITLE
RelStats and ActStats use wrong (unsorted) targets in FeatureVisualization method

### ISSUE THREAD

**Issue by maxdreyer** [rachtibat/zennit-crp#6]
Hi all,

I think the result of the methods **analyze_relevance** and **analyze_activation** from the **FeatureVisualization** class are not as expected.

Let us take the method (line 162 in visualization.py):
```
def analyze_relevance(self, rel, layer_name, concept, data_indices, targets):
    """
    Finds input samples that maximally activate each neuron in a layer and most relevant samples
    """

    d_c_sorted, rel_c_sorted, rf_c_sorted = self.RelMax.analyze_layer(rel, concept, layer_name, data_indices)
    
    self.RelStats.analyze_layer(d_c_sorted, rel_c_sorted, rf_c_sorted, layer_name, targets)
```
Here, the relevance values (identified by **rel_c_sorted**) of each channel are sorted in descending fashion. Therefore, **rel_c_sorted** has shape (batch_size, num_channels). However, for each channel, the values might be sorted differently (in different order) compared to another channel.

Afterwards, in **self.RelStats.analyze_layer(d_c_sorted, rel_c_sorted, rf_c_sorted, layer_name, targets)**, however, the values are assumed to not have been sorted:

```
def analyze_layer(self, d_c_sorted, rel_c_sorted, rf_c_sorted, layer_name, targets):

    t_unique = np.unique(targets)
    for t in t_unique:

        t_indices = np.where(targets == t)[0]

        d_c_t = d_c_sorted[t_indices]
        rel_c_t = rel_c_sorted[t_indices]
        rf_c_t = rf_c_sorted[t_indices]

        self.concatenate_with_results(layer_name, t, d_c_t, rel_c_t, rf_c_t)
        self.sort_result_array(layer_name, t)
```

Here, ultimately, the highest channel values are associated with the first target/value in **t_unique**, which is often not true.

In order to fix the behavior, we should take into account the actual target associated to each channel value. Maybe something like:

```
def analyze_relevance(self, rel, layer_name, concept, data_indices, targets):
    d_c_sorted, rel_c_sorted, rf_c_sorted, argsort = self.RelMax.analyze_layer(rel, concept, layer_name, data_indices)
    
    targets = torch.take(torch.Tensor(targets).to(argsort), argsort)
    self.RelStats.analyze_layer(d_c_sorted, rel_c_sorted, rf_c_sorted, layer_name, targets)
```
where **argsort** describes the sorting order and **targets** becomes a tensor of shape (batch_size, num_channels) indicating for each channel value the true target class. Method ** self.RelStats.analyze_layer** then needs to handle the different target shape.

**Comment by rachtibat** [comment]
Thanks for the detailed pull request.

In the method **self.RelStats.analyze_layer(d_c_sorted, rel_c_sorted, rf_c_sorted, layer_name, targets)**, my goal is to separate the sorted relevance values for each target.

At first, I collect all available targets
`t_unique = np.unique(targets)`
then, 
```
for t in t_unique:

        t_indices = np.where(targets == t)[0]

        d_c_t = d_c_sorted[t_indices]
        rel_c_t = rel_c_sorted[t_indices]
        rf_c_t = rf_c_sorted[t_indices]
```

for each target, I select all the relevance values **in sorted order**. As far as I can see, the sorting is not changed, only filtered out by the correct target.
Finally, I save the results for each target separately.

In the tutorial, the results of the statistics seem to be correct. Did you observe strange images when analyzing ImageNet?

Best

**Comment by rachtibat** [comment]
Thanks for the detailed description.

I added a new branch with your suggestion and some refactoring. Still needs some work, but anyone can pull your code, if he needs working stats now
